### ISSUE TITLE
[Bug] Timeouts in Serial communication

### ISSUE THREAD

**Issue by cguimaraes** [eclipse-zenoh/zenoh-pico#140]
### Describe the bug

Currently, timeouts are not supported in Serial transports.
Because of that, a read task might block forever while trying to read if the correspondent session was closed. Consequently, the `z_close` call will also block indefinitely.

### To reproduce

1. Start zenoh-pico session towards `zenohd` using a Serial locator.
2. Close the session.
3. The task closing the session will block indefinitely.

### System info

N/A

**Comment by cguimaraes** [comment]
#362 is partially addressing this issue on `esp-idf` port.

**Comment by jean-roland** [comment]
#383 Solves this for `esp-idf` platform
