### ISSUE TITLE
[Bug] Zenoh-Pico UDP Peer frees unitialized endpoint

### ISSUE THREAD

**Issue by PetervdPerk-NXP** [eclipse-zenoh/zenoh-pico#166]
### Describe the bug

On my NuttX target I was facing hardfault because `_Z_ERR_TRANSPORT_OPEN_FAILED`. It turns out when clearing the error it wants to free() the UDP transport link.
`_z_free_endpoint_udp(&self->_socket._udp._lep);`
But `_lep` has not been intialized since it failed to allocate causing it to free a random pointer.
A hotfix for me is to initialize `_z_link_t` to 0 so that when `freeaddrinfo()` get called it will ignore it since `_lep` pointer is already NULL.

### Stack trace of harddfault
![image](https://user-images.githubusercontent.com/57130844/221890596-b815bdf2-520b-493a-a559-b6b7c213d602.png)

### To reproduce

Create a peer session
```
	const char *keyexpr = "rt/zenoh_log_test";
	const char *mode = "peer";
    const char *locator = "udp/224.0.0.225:7447#iface=eth0";

	z_owned_config_t config = z_config_default();
	zp_config_insert(z_config_loan(&config), Z_CONFIG_MODE_KEY, z_string_make(mode));

	if (locator != NULL) {
		zp_config_insert(z_config_loan(&config), Z_CONFIG_PEER_KEY, z_string_make(locator));
	}

	printf("Opening session...\n");
	z_owned_session_t s = z_open(z_config_move(&config));
```

### System info

Zenoh-pico
NuttX 11.0

**Comment by cguimaraes** [comment]
@PetervdPerk-NXP help validating this one on your setup also welcome 👍
