### ISSUE TITLE
[Bug] Z_DYNAMIC_MEMORY_ALLOCATION doesn't work

### ISSUE THREAD

**Issue by hairymnstr** [eclipse-zenoh/zenoh-pico#178]
### Describe the bug

Trying to test out a build of zenoh pico on a microcontroller with limited resources I tried enabling dynamic memory allocation, but in transport.c:
https://github.com/eclipse-zenoh/zenoh-pico/blob/master/src/transport/transport.c#L102

This makes `dbuf_size` zero, however the default size when allocating an expandable `z_wbuf` is `Z_IOSLICE_SIZE`( = 128) so a couple of lines later (https://github.com/eclipse-zenoh/zenoh-pico/blob/master/src/transport/transport.c#L112) the test fails resulting in an "out of memory" error.  It's not really out of memory, it's just that the size of the two expandable wbufs are 128 not zero like the request.  I'm not deep enough into the code to figure out the best resolution, maybe just making `dbuf_size` 128 (`Z_IOSLICE_SIZE`) by default?  For now I've worked around by adding `-DZ_FRAG_MAX_SIZE=65536` to my CMake file and leaving dynamic allocation disabled.

### To reproduce

* Add -DZ_DYNAMIC_MEMORY_ALLOCATION=1 to the compile options.
* Try and connect a unicast transport.
* It fails with `_Z_ERR_SYSTEM_OUT_OF_MEMORY`

### System info

arm-none-eabi-gcc (GNU Arm Embedded Toolchain 10.3-2021.10) 10.3.1 20210824 (release)
Zenoh pico commit 5b4734114fad6f7fc484322b53f0f02872171ac5

**Comment by cguimaraes** [comment]
I just provided a fix for it: #179 
We would appreciate if you can validate it in your setup / scenario.

**Comment by cguimaraes** [comment]
Thank you @hairymnstr for the validation.

As of today, the impact of this option is mostly for fragmented messages.
Thus, for the remaining operation it should behave the same with or without dynamic memory allocation.
We plan to revisit this in the future, but we are focusing on other priorities for the short-term roadmap.
