### ISSUE TITLE
difference in z_drop macro in zenohc and zenoh-pico

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh-pico#181]
In zenoh-pico macro z_drop calls one of z_XXX_drop functions:

https://github.com/eclipse-zenoh/zenoh-pico/blob/master/include/zenoh-pico/api/macros.h#L52-L65

in zenoh-c the same macro calls higher level function depending on type, if available (z_close for session, z_udeclare_subscriber for subscriber)

https://github.com/eclipse-zenoh/zenoh-c/blob/master/include/zenoh_macros.h#L16-L35

Both approaches makes sense but it's important to have same logic in both projects.

Also for the zenoh-cpp project the zenoh-c approach is preferrable, as it allows to make correct resource cleaning with single template.

**Comment by cguimaraes** [comment]
In Zenoh-Pico, the reason for calling `z_XXX_drop` is to have the way of using the ownership handlers when C11 (or generics) are not supported.

I would prefer these semantics, otherwise the API usage between C99 and C11 will be cumbersome for some users.
