### ISSUE TITLE
Add z_ping and z_pong examples

### ISSUE THREAD

**Issue by Mallets** [eclipse-zenoh/zenoh-pico#209]
### Describe the feature

Add [z_ping](https://github.com/eclipse-zenoh/zenoh/blob/master/examples/examples/z_pong.rs) and [z_pong](https://github.com/eclipse-zenoh/zenoh/blob/master/examples/examples/z_pong.rs) also in zenoh-pico in the same way as done in Rust.

**Comment by cguimaraes** [comment]
Fixed by #212
