### ISSUE TITLE
[Bug] SegFault when running z_ping & z_pong examples

### ISSUE THREAD

**Issue by imstevenpmwork** [eclipse-zenoh/zenoh-pico#226]
### Describe the bug

In latest ```master``` the z_ping and z_pong examples result in segmentation fault:

```
[1]    54091 segmentation fault  ./z_pong
```

However, this only happens if there is no ```zenohd``` running.

Possible cause: No ```z_check()``` after creating an owned session

### To reproduce

1. Fresh build from the 9b663d5b8aa0e7aa35f0da9285622e0c8cc25649 commit
2. Run ./z_ping or ./z_pong

### System info

System:
* OS: macOS 13.4.1 22F82 arm64
* CPU & GPU: Apple M2

Zenoh:

```
λ › zenohd --version                                                                                                                 ~
[2023-07-04T13:10:59Z INFO  zenohd] zenohd v0.7.0-rc-401-gb9103c3d built with rustc 1.70.0 (90c541806 2023-05-31)
The zenoh router v0.7.0-rc-401-gb9103c3d built with rustc 1.70.0 (90c541806 2023-05-31)
```

**Comment by cguimaraes** [comment]
Just give a quick look at the example, and I believe you are right on the possible cause.
I will provide a PR in a while.
