### ISSUE TITLE
[Bug] z_ping and z_pong examples hanging

### ISSUE THREAD

**Issue by imstevenpmwork** [eclipse-zenoh/zenoh-pico#227]
### Describe the bug

Related to https://github.com/eclipse-zenoh/zenoh-pico/issues/226.
In the latest ```master``` both z_ping and z_pong example hang, even when there is a zenoh running. The order in which they are executed seem to have no effect.

### To reproduce

1. Fresh build from the 9b663d5b8aa0e7aa35f0da9285622e0c8cc25649 commit
2. Run zenohd
3. Run ./z_ping or ./z_pong

### System info

System:
* OS: macOS 13.4.1 22F82 arm64
* CPU & GPU: Apple M2

Zenoh:

```
λ › zenohd --version                                                                                                                 ~
[2023-07-04T13:10:59Z INFO  zenohd] zenohd v0.7.0-rc-401-gb9103c3d built with rustc 1.70.0 (90c541806 2023-05-31)
The zenoh router v0.7.0-rc-401-gb9103c3d built with rustc 1.70.0 (90c541806 2023-05-31)
```

**Comment by cguimaraes** [comment]
This is most likely because the `read` and `lease` tasks were not started.
I will provide a PR in a while.
