### ISSUE TITLE
[Bug] Installation fails when building from source

### ISSUE THREAD

**Issue by imstevenpmwork** [eclipse-zenoh/zenoh-pico#234]
### Describe the bug

After
```
make
sudo make install
```
 I got:
 ```
-- Up-to-date: /usr/local/include/zenoh-pico/session/subscription.h
-- Up-to-date: /usr/local/include/zenoh-pico/session/publication.h
CMake Error at build/cmake_install.cmake:65 (file):
  file cannot create directory: /cmake/zenohpico.  Maybe need administrative
  privileges.
```

### To reproduce

Follow the instructions in the readme for building from source

### System info

OS: macOS 13.4.1 22F82 arm64

**Comment by Mallets** [comment]
To install it under `/usr/local` you need administrative privileges. Can you try with `sudo`?

**Comment by imstevenpmwork** [comment]
Oh I did, I forgot to mention that.
I did run it with sudo, yea
