### ISSUE TITLE
[Bug] Zenoh Pico runs out of memory on Arduino

### ISSUE THREAD

**Issue by p-avital** [eclipse-zenoh/zenoh-pico#261]
### Describe the bug

Defragmentation buffer seems to allocate too much memory for the arduino, ideally it shouldn't allocate on its own.

### To reproduce

Local zenoh demo

### System info

Arduino board

**Comment by cguimaraes** [comment]
@p-avital shall we close this issue.
Did you check if by enabling dynamic memory allocations, the issue is also witnessed?
