### ISSUE TITLE
Align z_time and z_clock primitives for Windows with Rust implementation

### ISSUE THREAD

**Issue by cguimaraes** [eclipse-zenoh/zenoh-pico#272]
### Describe the feature

**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Currently on Windows, `z_time` and `z_clock` primitives are implemented in the same way. However, they have different purposes in mind, as mentioned in #270 .

**Additional context**
From @Mallets in #269: 
> For Windows, in [Rust](https://doc.rust-lang.org/std/time/struct.Instant.html#underlying-system-calls) they base the clock implementation on [QueryPerformanceCounter](https://learn.microsoft.com/en-us/windows/win32/api/profileapi/nf-profileapi-queryperformancecounter). We might think about updating the Windows port to that but I'd leave it as a new PR.

**Comment by Mallets** [comment]
Closed by #310
