### ISSUE TITLE
remove "using namespace std" statement [Bug] 

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh-pico#276]
It's incorrect to expose "using namespace std" in header here:
https://github.com/eclipse-zenoh/zenoh-pico/blob/master/include/zenoh-pico/collections/pointer.h#L29
This affects compilation of other projects which may purposedly avoid including ``std`` namepace.See explanation here 
https://stackoverflow.com/questions/5849457/using-namespace-in-c-headers

Unfortunately just removing this line is not enough because macro ``_Z_POINTER_DEFINE`` accesses ``memory_order_relaxed`` without ``std`` prefix and we can't just add ``std::`` to it as this should work with C code too. A bit more clever solution is required.

**Comment by cguimaraes** [comment]
@milyin provided a fix in #281
