### ISSUE TITLE
RefCount for zenoh entities

### ISSUE THREAD

**Issue by imstevenpmwork** [eclipse-zenoh/zenoh-pico#312]
### Describe the feature

As an example, currently if we call ```z_publisher_put(...)``` after having closed the session we get a segmentation fault:
```
zp_stop_read_task(...);
zp_stop_lease_task(...);
z_close(...);
...
z_publisher_put(...)
```
This happens because ```z_publisher_t``` maintains a reference to the session, but if this one was closed, the reference is unchanged. This is only one of the examples and even thought the order of these calls doesn't make sense, our API should be robust enough to avoid these types of bad-usage.
This can be solved by implementing a reference counting mechanism for the declared zenoh entities. The architecture is still to be defined, but I'm opening this issue to keep track of it.

**Comment by cguimaraes** [comment]
I believe that @p-avital implemented (or is implementing) the baseline for a refcount mechanism.

In this case, the `close` call would be postponed until no references to the session exist.

**Comment by jean-roland** [comment]
As of now, refcounting is present but only used for subscriptions and queryables

**Comment by imstevenpmwork** [comment]
Solved by https://github.com/eclipse-zenoh/zenoh-pico/pull/322
