### ISSUE TITLE
User Attachments

### ISSUE THREAD

**Issue by p-avital** [eclipse-zenoh/zenoh-pico#335]
### Describe the feature

User attachments were introduced in Zenoh 0.10.1.

They should now be added to Zenoh Pico.
- [x] Pub/Sub support
- [x] Queryable support
- [x] Reply support

**Comment by Mallets** [comment]
@jean-roland I think we can close this issue, isn't it?

**Comment by jean-roland** [comment]
Yeah it can be closed
