### ISSUE TITLE
Review of the protocol

### ISSUE THREAD

**Issue by Mallets** [eclipse-zenoh/zenoh-pico#344]
### Describe the feature

As part of the effort for the next [Zenoh 1.0.0 release](https://github.com/eclipse-zenoh/roadmap/issues/116), a full review of the existing wire protocol is desirable. 
This PR is a sister PR of https://github.com/eclipse-zenoh/zenoh/issues/673.

This includes aspects like (but not limited to):
- [x] Entity ID 
- [x] Encoding field
- [x] Declarations
- [x] Verbatim chunks impact on Declarations
- [x] SampleKind in replies (linked to https://github.com/eclipse-zenoh/zenoh/pull/717)

Changes will be first pushed to https://github.com/eclipse-zenoh/zenoh-pico/tree/protocol_changes branch.

**Comment by Mallets** [comment]
@jean-roland I believe this issue can be closed now based on the recent development in `dev/1.0.0`.

**Comment by jean-roland** [comment]
Agreed, you can close it.
