### ISSUE TITLE
z_mutex_init and other functions returns positive error values [Bug] 

### ISSUE THREAD

**Issue by milyin** [eclipse-zenoh/zenoh-pico#358]
### Describe the bug

```
int8_t zp_mutex_init(zp_mutex_t *m) { return pthread_mutex_init(m, 0); }
int8_t zp_mutex_free(zp_mutex_t *m) { return pthread_mutex_destroy(m); }
```
The error values returned by `pthread_mutex_init` can be positive: 
https://pubs.opengroup.org/onlinepubs/7908799/xsh/pthread_mutex_init.html
https://github.com/openbsd/src/blob/8700ed7d87c3b82368687dfae3281b306aecbe66/sys/sys/errno.h

But in zenoh c interface it's assumed that error value should always be negative.

### To reproduce

-

### System info

-

**Comment by sashacmc** [comment]
@milyin please assign it to me
