### ISSUE TITLE
[Bug] setsockopt SO_RCVTIMEO not working in Windows

### ISSUE THREAD

**Issue by pdematteis** [eclipse-zenoh/zenoh-pico#409]
### Describe the bug

In network.c, `_z_open_udp_unicast()` calls `setsockopt()` passing a `z_time_t` value, while in Windows it should be `DWORD` type.
Fixed by using:
```
#ifdef WIN32
        DWORD tv = tout;
#else
        z_time_t tv;
        tv.time = tout / (uint32_t)1000;
        tv.millitm = tout % (uint32_t)1000;
#endif
```

### To reproduce

Start either a publisher or a subscriber with no parameters in Windows without zenohd running.
The application will stuck in Opening session... and the expected timeout is not honored.

### System info

Windows 11

**Comment by jean-roland** [comment]
Hello @pdematteis, thanks for notifying us, I'll investigate the issue and open a PR accordingly.
