### ISSUE TITLE
Confused about reliability

### ISSUE THREAD

**Issue by pdematteis** [eclipse-zenoh/zenoh-pico#412]
### Describe the bug

Reliability is defined as
```
typedef enum { Z_RELIABILITY_BEST_EFFORT = 1, Z_RELIABILITY_RELIABLE = 0 } z_reliability_t;
#define Z_RELIABILITY_DEFAULT Z_RELIABILITY_RELIABLE
```

`_z_unicast_send_n_msg()` does call `_z_t_msg_make_frame_header()` by passing `reliability` as the `is_reliable` parameter.
The problem is that `is_reliable` is of type `_Bool`, thus `Z_RELIABILITY_RELIABLE` evaluates to false and the `_Z_FLAG_T_FRAME_R` flag isn't set.

Is this a bug or for some reason it is by design?

### To reproduce

Run any of the examples.

### System info

Any

**Comment by jean-roland** [comment]
This seems suspicious, I'll investigate
