### ISSUE TITLE
Implement slice map <-> payload conversion

### ISSUE THREAD

**Issue by sashacmc** [eclipse-zenoh/zenoh-pico#443]
### Describe the release item

 - z_bytes_serialize_from_slice_map [include/zenoh_commons.h#L1327](https://github.com/eclipse-zenoh/zenoh-c/blob/6ba997f5a91c55ddc7f849c852d50bb220fcb408/include/zenoh_commons.h#L1327)
 - z_bytes_serialize_from_slice_map_copy [include/zenoh_commons.h#L1333](https://github.com/eclipse-zenoh/zenoh-c/blob/6ba997f5a91c55ddc7f849c852d50bb220fcb408/include/zenoh_commons.h#L1333)
 - z_bytes_deserialize_into_slice_map [include/zenoh_commons.h#L1113](https://github.com/eclipse-zenoh/zenoh-c/blob/6ba997f5a91c55ddc7f849c852d50bb220fcb408/include/zenoh_commons.h#L1113)

**Comment by DenisBiryukov91** [comment]
I think this is not needed and also should be removed from zenoh-c. Slice map was introduce as a way to pass key-value pairs (mostly for attachment), but it is no longer required since we can use z_bytes_iterator.
