### ISSUE TITLE
Implement message helpers

### ISSUE THREAD

**Issue by Mallets** [eclipse-zenoh/zenoh-pico#47]
Implement internal message helpers for creating zenoh messages and setting their content.
This would increase robustness of the codebase to any potential change in the protocol definition.

**Comment by Mallets** [comment]
Message builders have been implemented in the multicast-support branch: 767ea1517b909d4a104761fe50ed426ddf2491cc
This issue will be closed once the [multicast-support branch](https://github.com/eclipse-zenoh/zenoh-pico/tree/multicast-support) is merged into master.

**Comment by cguimaraes** [comment]
To be closed when PR #58 is merged.
