### ISSUE TITLE
Add missed z_view_keyexpr_* methods

### ISSUE THREAD

**Issue by sashacmc** [eclipse-zenoh/zenoh-pico#472]
### Describe the release item

 - z_view_keyexpr_from_str_autocanonize [include/zenoh_commons.h#L3541](https://github.com/eclipse-zenoh/zenoh-c/blob/6ba997f5a91c55ddc7f849c852d50bb220fcb408/include/zenoh_commons.h#L3541)
 - z_view_keyexpr_from_substr [include/zenoh_commons.h#L3567](https://github.com/eclipse-zenoh/zenoh-c/blob/6ba997f5a91c55ddc7f849c852d50bb220fcb408/include/zenoh_commons.h#L3567)
 - z_view_keyexpr_from_substr_autocanonize [include/zenoh_commons.h#L3581](https://github.com/eclipse-zenoh/zenoh-c/blob/6ba997f5a91c55ddc7f849c852d50bb220fcb408/include/zenoh_commons.h#L3581)
 - z_view_keyexpr_from_substr_unchecked [include/zenoh_commons.h#L3596](https://github.com/eclipse-zenoh/zenoh-c/blob/6ba997f5a91c55ddc7f849c852d50bb220fcb408/include/zenoh_commons.h#L3596)

**Comment by sashacmc** [comment]
z_view_keyexpr_from_str_autocanonize - done

z_view_keyexpr_from_substr* - can't be done without significant rework, currently keyexpr _suffix stored as pointer to null terminated string, to allow creating view_keyexpr from substr it should be changed to store _z_string_t.

**Comment by jean-roland** [comment]
@milyin could you please assign it to me?
