### ISSUE TITLE
Mutexes accessed although not initialized

### ISSUE THREAD

**Issue by philhoeb** [eclipse-zenoh/zenoh-pico#477]
### Describe the bug

If _z_open() fails it can happen that _z_session_rc_drop() is called and mutexes are accessed although z_mutex_init() has never been called.
At least with FreeRTOS this leads to problems. Either asserts fail (if configured) or you end up in a hard fault when the null pointer is dereferenced.

### To reproduce

1. Do not start a Zenoh router
2. Call z_open() on STM32

### System info

- Platform: STM32 with FreeRTOS
- Zenoh: 1.0.0.3

**Comment by jean-roland** [comment]
Will look into this, thanks for noticing us.

**Comment by jean-roland** [comment]
Hello @philhoeb, could you just tell me what zenoh platform is used in your setup? The list can be found in `include/zenoh-pico/system/platform-common.h`.
