### ISSUE TITLE
Fifo/Ring handlers behavior for 0 buffer size

### ISSUE THREAD

**Issue by DenisBiryukov91** [eclipse-zenoh/zenoh-pico#572]
### Describe the feature

Currently Fifo handler with 0 buffer size will block indefinitely (behavior different from Zenoh-Rust where it turns in rendezvous channel), while Ring handler with 0 size will simply drop the messages (same as in Zenoh-Rust)
For simplicity, it would probably make sense to forbid creation of handlers with 0 buffer size.

**Comment by sashacmc** [comment]
@milyin please assign it to me.
