### ISSUE TITLE
Protocol refactoring

### ISSUE THREAD

**Issue by Mallets** [eclipse-zenoh/zenoh-pico#60]
A new version of the zenoh protocol is under development. The new version is expected to improve extensibility and flexibility allowing zenoh to effectively address a multitude of scenarios.

This issue is to keep track of the ongoing activities.
It will be closed once the protocol is implemented and merged in the master branch.

This issue is linked to the main [zenoh issue](https://github.com/eclipse-zenoh/zenoh/issues/157).

**Comment by cguimaraes** [comment]
Under development in https://github.com/eclipse-zenoh/zenoh-pico/tree/new-protocol

**Comment by cguimaraes** [comment]
Finished with PR https://github.com/eclipse-zenoh/zenoh-pico/pull/243
