### ISSUE TITLE
Implement Connection Restoration Mechanism

### ISSUE THREAD

**Issue by sashacmc** [eclipse-zenoh/zenoh-pico#767]
### Describe the release item

Issue:
When network disruptions occur (e.g., due to network problems or router restarts), zenoh-pico currently loses the connection without any attempt to restore it. Unlike zenoh-c, which includes a mechanism to handle such disruptions and automatically reconnect, zenoh-pico lacks this functionality, potentially causing silent data loss and communication gaps.

Expected Behavior:
zenoh-pico should detect network interruptions and, upon reestablishing connectivity, automatically restore its connection without requiring manual intervention. This would bring zenoh-pico in line with zenoh-c in terms of resilience and reliability.

**Comment by sebglatz** [comment]
This feature is a high priority for us. 
Could you share an estimated timeline for its completion? 
Additionally, is there any way we can assist?

**Comment by sashacmc** [comment]
Hi @sebglatz, we've already started working on it but there have been a few blockers, I'm hoping we can continue working on it next week and if nothing unexpected comes up by the end of the week I'd like to have it in main.
