### ISSUE TITLE
Serial (RS-232)-like transport 

### ISSUE THREAD

**Issue by gabrik** [eclipse-zenoh/zenoh-pico#98]
### Describe the feature

Zenoh(and pico) currently support transport mostly "networking" protocols (TCP, UDP, and so on).
It would be nice for zenoh-pico also to support serial-based communications. 
A PR is already open in Zenoh to include this support. https://github.com/eclipse-zenoh/zenoh/pull/274 
The low-level framing and serialization are handled by https://github.com/ZettaScaleLabs/z-serial

**Comment by cguimaraes** [comment]
Provided support for Mbed and tested with the Zenoh PR posted in the initial post.
https://github.com/eclipse-zenoh/zenoh-pico/pull/100
